name: Secure DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write  # OIDC用
  contents: read
  security-events: write  # CodeQL用

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: sample-app
  IMAGE_TAG: latest

jobs:
# ===== 1. Lint（Ruff）===== #
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Lint
        run: ruff check . || true  # ruff が failed を返しても後続に進む

# ===== 2. Format（Black）===== #
  format:
    name: Black Format Check
    runs-on: ubuntu-latest
    needs: lint   # lint成功後に実行

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Black
        run: pip install black

      - name: Run Black (check mode)
        run: black --check . || true  # Black が exit 1 を返しても後続に進む

# ===== 3. SAST（CodeQL）===== #
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: format   # format成功後に実行

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

# =====  4. Build / Trivy Scan / Push to ECR ===== #
  build_scan_push:
    name: Build, Scan and Push
    runs-on: ubuntu-latest
    needs: codeql  # CodeQL成功後に実行
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      # Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

      # Trivy
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          format: table
          exit-code: 1

      # AWS OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::150870381824:role/github-actions-devsecops-role
          aws-region: ap-northeast-2

      # ECR login
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }}

      # Push image to ECR
      - name: Push Docker Image to ECR
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

