name: Secure DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write         # OIDC 用（追加）
  contents: read
  security-events: write  # CodeQL 用

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: sample-app
  IMAGE_TAG: latest

jobs:
  # ===== 1. Ruff + Black (Lint/Format) =====
  lint:
    name: Ruff & Black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Python & tools
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff & Black
        run: |
          pip install ruff black

      # Ruff (lint)
      - name: Run Ruff
        run: ruff check . || true   # Ruff failed しても後続に進む
      # Black (format check)
      - name: Run Black (check mode)
        run: black --check . || true  # Black が exit 1 を返しても後続に進む
  
  # ===== 2. CodeQL（Python SAST）===== #
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: lint   # Linter通過後に実行
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # ===== 3. Build/Scan/Push　===== #
  build_scan_push:
    name: Build, Scan and Push
    runs-on: ubuntu-latest
    needs: codeql
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      # Build
      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

      # Trivy
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          format: table
          exit-code: 1

      # AWS Auth
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::150870381824:role/github-actions-devsecops-role
          aws-region: ap-northeast-2  

      # ECR login
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ env.AWS_REGION }} 

      # Push
      - name: Push Docker Image to ECR
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
